---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-automute-us
  namespace: cert-manager
spec:
  secretName: wildcard-automute-us-tls
  duration: 2160h
  renewBefore: 360h
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.automute.us"
    - "automute.us"
