---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-cronjob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cronjob
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-cronjob
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cronjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cronjob
subjects:
  - name: cert-manager-cronjob
    namespace: cert-manager-cronjob
    kind: ServiceAccount

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cert-manager-cronjob
spec:
  schedule: "33 0,12 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: cert-manager-cronjob
          containers:
            - name: hyperkube
              command: ["/bin/bash"]
              image: "eu.gcr.io/google_containers/hyperkube:v1.14.1"
              args:
                [
                  "-xc",
                  'for i in $(./kubectl get ns -o json | jq -r ".items[].metadata.name" | grep -v cert-manager); do ./kubectl get secret -o json --namespace cert-manager wildcard-automute-us-tls --export | jq ''del(.metadata.namespace)'' | ./kubectl apply -n ${i} -f -; done',
                ]
